site_name: nerd.dad
site_description: a blog for all nerd dads
site_url: https://nerd.dad/
copyright: Copyright &copy; 2024 - 2050 nerd.dad
repo_url: https://github.com/nerddotdad/nerd.dad
repo_name: nerddotdad/nerd.dad
edit_uri: edit/main/docs/

## Nav is placeholder for now
# nav:
#   - Section:
#     - section/index.md 
#     - Page n: section/page-n.md

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view
    - announce.dismiss
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - content.tooltips

watch:
  - overrides

plugins:
  - search
  - blog
  # - include_dir_to_nav
  # - mkdocs_github_changelog
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: nerddotdad/nerd.dad
      branch: main
  # - termynal: # Really promosing plugin but at this time it does not play well. https://termynal.github.io/termynal.py/
  #     title: bash
  #     buttons: macos
  #     prompt_literal_start:
  #       - "$"
  - mike:
      alias_type: copy
  - tags
  - macros:
      module_name: ipesre-modules
      # on_error_fail: true  # Optional, will make build fail on errors
      # on_undefined: strict
      include_yaml:
        ### services
        - docs/services/aod/config.yaml
        - docs/services/cors/config.yaml
        - docs/services/dataeditor/config.yaml
        - docs/services/dataloader/config.yaml
        - docs/services/example/config.yaml
        - docs/services/ots/config.yaml
        - docs/services/wta/config.yaml
        ### user_guides config
        - docs/developer_guides/release_management/config.yaml
        - docs/developer_guides/getting_started/config.yaml
  - autorefs:
      resolve_closest: true
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: true
      href: "mailto:{email}"
      count_empty_lines: false
      fallback_to_empty: true
      sort_authors_by: name
      authorship_threshold_percent: 10
      exclude:
        - index.md
      enabled: true
      enabled_on_serve: true
#      strict: true

extra:
  version:
    provider: mike
    default: latest
    alias: true
  social:
  - icon: fontawesome/brands/discord
    link: https://discordapp.com/users/64831697186721792
    name: My Discord
  - icon: fontawesome/brands/github
    link: https://github.com/nerddotdad
    name: nerd.dad github
  - icon: fontawesome/solid/cubes
    link: https://github.com/nerddotdad/truecharts
    name: nerd.dad cluster
  generator: false
  annotate:
    json: [.s2]

extra_javascript:
  - 'custom/js/custom.js'
extra_css:
  - 'custom/stylesheets/custom.css'

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: ['docs']
      auto_append:
        - ref/admin/abbreviations.md