site_name: nerd.dad
site_description: a blog for all nerd dads
site_url: https://nerd.dad/
copyright: Copyright &copy; 2024 - 2050 nerd.dad
repo_url: https://github.com/nerddotdad/nerd.dad
repo_name: nerddotdad/nerd.dad
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Blog: blog/index.md

theme:
  name: material
  logo: attachments/main/logo_transparent.png
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: test)"
      scheme: test
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.view
    - announce.dismiss
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - content.tooltips

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

watch:
  - overrides
  - includes

hooks:
  - hooks/socialmedia.py

plugins:
  - search
  - blog:
      pagination_per_page: 5

  - tts-amazon-polly:
      output_dir: "audio"
      voice_id: "Joanna"

  # - include_dir_to_nav
  # - mkdocs_github_changelog
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: nerddotdad/nerd.dad
      branch: main
  # - termynal: # Really promosing plugin but at this time it does not play well. https://termynal.github.io/termynal.py/
  #     title: bash
  #     buttons: macos
  #     prompt_literal_start:
  #       - "$"
  - mike:
      alias_type: symlink
  - tags:
      tags_file: tags.md
  - macros
  - autorefs:
      resolve_closest: true
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: true
      href: "mailto:{email}"
      count_empty_lines: false
      fallback_to_empty: true
      sort_authors_by: name
      authorship_threshold_percent: 10
      exclude:
        - index.md
      enabled: true
      enabled_on_serve: true
#      strict: true

extra:
  audio_dir: "audio"
  version:
    provider: mike
    default: latest
    alias: true
  social:
  - icon: fontawesome/brands/discord
    link: https://discordapp.com/users/64831697186721792
    name: My Discord
  - icon: fontawesome/brands/github
    link: https://github.com/nerddotdad
    name: nerd.dad github
  - icon: fontawesome/solid/cubes
    link: https://github.com/nerddotdad/truecharts
    name: nerd.dad cluster
  generator: false
  annotate:
    json: [.s2]

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.blocks.caption
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        

### Example Configuration ###

# Custom Homepage Elements
home_cover_image: attachments/main/me_small.png # This path starts at your root mkdocs directory.
home_tagline: nerd.dad
home_description: |
  My online space for sharing my passion for Site Reliability Engineering and more.

# Gradient Color
home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

# # Custom Homepage Button(s)
# home_button1_name: About Me                  # Comment this parameter out to remove the button.
# home_button1_url: about_me                      # This path starts at your root mkdocs directory.
# home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
# home_button1_icon: people                        # Options: "people", "gear", "image"
# home_button1_blurb: |                            # Short description of this button / section.
#   About Me

home_button2_name: My Podcast   # Comment this parameter out to remove the button.
home_button2_url: podcast    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: |         # Short description of this button / section.
  Check out my podcast

home_button3_name: Blog   # Comment this parameter out to remove the button.
home_button3_url: blog    # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: image      # Options: "people", "gear", "image"
home_button3_blurb: |         # Short description of this button / section.
  Head over to my blog

# Custom Homepage Panel(s)

home_panel1_icon: image      # Options: "people", "gear", "image"
home_panel1_title: Being a Dad   # Comment this parameter out to remove the button.
# home_panel1_url: blog/index.md    # This path starts at your root mkdocs directory.
# home_panel1_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_panel1_blurb: |         # Short description of this button / section.
  Dirty Diapers<br>Shows on Repeat<br>Coffee Addiction

home_panel2_icon: image      # Options: "people", "gear", "image"
home_panel2_title: Being a Nerd   # Comment this parameter out to remove the button.
# home_panel2_url: blog/index.md    # This path starts at your root mkdocs directory.
# home_panel2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_panel2_blurb: |         # Short description of this button / section.
  Site Reliability Engineer<br>System Administration<br>Development

home_panel3_icon: test      # Options: "people", "gear", "image"
home_panel3_title: Being a Nerd Dad   # Comment this parameter out to remove the button.
# home_panel3_url: blog/index.md    # This path starts at your root mkdocs directory.
# home_panel3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_panel3_blurb: |         # Short description of this button / section.
  Let's get our kiddos involved!<br>Sharing what we're excited about is one of the best parts of being a dad!

# Homepage Code Execution
home_execute_js: | # Javascript to execute when accessing the homepage
  console.log("This is an example!");