name: Build/Publish Latest Release Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "itzteajay@gmail.com"
      - name: Parse Version
        env: 
          commit_message: echo "${{ github.event.head_commit.message }}"
        id: parse
        run: echo "version=$(echo "$commit_message" | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
      - name: Test Version
        run: |
          echo ${{ steps.split.outputs.version }}
      # - name: Build Docs Website
      #   run: mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest